FROM apache/airflow:2.10.5-python3.10

USER airflow

ENV AIRFLOW_HOME=/opt/airflow
ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow"

COPY ./app $AIRFLOW_HOME/app
COPY ./airflow/dags $AIRFLOW_HOME/dags
COPY .env $AIRFLOW_HOME/.env
COPY entrypoint.sh $AIRFLOW_HOME/entrypoint.sh
